### ISSUE TITLE
[Bug] 编译成Docker镜像后 提示无法找到库文件

### ISSUE THREAD

**Issue by ertu426** [ViewFaceCore/ViewFaceCore#57]
**简明描述**
项目是 dotnet6 Wab Api 项目  在我WIndows 系统中运行没有任何问题 但编译成 Docker镜像后 会提示找不到每个库文件

Docker 镜像是基于 <code>mcr.microsoft.com/dotnet/aspnet:6.0-alpine</code> 来创建的

**开发环境**
 - 目标框架: docker
 - 项目类型 ASP.NET Core API

**相关包清单**
 - ViewFaceCore 0.3.8
 - ViewFaceCore.all_models 6.0.7
 - ViewFaceCore.Extension.SkiaSharp 0.3.7
 - ViewFaceCore.runtime.linux.arm64 6.0.7
 - ViewFaceCore.runtime.ubuntu.20.04.x64 6.0.7
 - ViewFaceCore.runtime.win.x64 6.0.7

**运行环境**
 - 操作系统: Windows 11 专业版
 - 系统类型: 64 位操作系统, 基于 x64 的处理器
 - 处理器: Intel(R) Core(TM) i7-9750H

**附件**
<details><summary>日志片段</summary>
<pre>
[15:06:00 INF] Now listening on: http://[::]:80
[15:06:00 INF] Application started. Press Ctrl+C to shut down.
[15:06:00 INF] Hosting environment: Production
[15:06:00 INF] Content root path: /app/
[15:07:02 INF] Request starting HTTP/1.1 OPTIONS http://localhost:4001/faceinfo - -
[15:07:02 INF] CORS policy execution successful.
[15:07:02 INF] HTTP OPTIONS /faceinfo responded 204 in 16.3145 ms
[15:07:02 INF] Request finished HTTP/1.1 OPTIONS http://localhost:4001/faceinfo - - - 204 - - 151.5146ms
[15:07:02 INF] Request starting HTTP/1.1 POST http://localhost:4001/faceinfo application/json 258508
[15:07:02 INF] CORS policy execution successful.
[15:07:02 INF] Executing endpoint 'face_system.Controllers.FaceInfoController.Create (face_system)'
[15:07:02 INF] Route matched with {action = "Create", controller = "FaceInfo"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Create(face_system.Domain.FaceInfoDtos.FaceInfoAddDto) on controller face_system.Controllers.FaceInfoController (face_system).
[15:07:03 WRN] System.TypeInitializationException: The type initializer for 'ViewFaceCore.Native.ViewFaceNative' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library '/app/viewfacecore/linux/x64/libSeetaMaskDetector200.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libSeetaAuthorize.so: No such file or directory (needed by /app/viewfacecore/linux/x64/libSeetaMaskDetector200.so)
   at System.Runtime.InteropServices.NativeLibrary.LoadFromPath(String libraryName, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at ViewFaceCore.Native.ViewFaceNative..cctor()
   --- End of inner exception stack trace ---
   at ViewFaceCore.Native.ViewFaceNative.GetFaceDetectorHandler(Double faceSize, Double threshold, Double maxWidth, Double maxHeight, Int32 deviceType)
   at ViewFaceCore.Core.FaceDetector..ctor(FaceDetectConfig config)
   at face_system.Face.FaceInfoHelper.GetExtract(String imagePath) in /src/Face/face_system.Face/FaceInfoHelper.cs:line 9
   at face_system.Controllers.FaceInfoController.Create(FaceInfoAddDto faceInfo) in /src/face_system/Controllers/FaceInfoController.cs:line 99
[15:07:03 INF] Executing BadRequestObjectResult, writing value of type '<>f__AnonymousType1`3[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
[15:07:03 INF] Executed action face_system.Controllers.FaceInfoController.Create (face_system) in 698.3592ms
[15:07:03 INF] Executed endpoint 'face_system.Controllers.FaceInfoController.Create (face_system)'
[15:07:03 INF] HTTP POST /faceinfo responded 400 in 890.1262 ms
[15:07:03 INF] Request finished HTTP/1.1 POST http://localhost:4001/faceinfo application/json 258508 - 400 - application/json;+charset=utf-8 901.1779ms
</pre>
</details>

<details><summary>代码片段</summary>
<pre>
    public List<float> GetExtract(string imagePath)
    {
        using var bitmap = SKBitmap.Decode(imagePath);
        using FaceDetector faceDetector = new FaceDetector();
        using FaceLandmarker faceMark = new FaceLandmarker();
        using FaceRecognizer faceRecognizer = new FaceRecognizer();

        FaceImage faceImage = bitmap.ToFaceImage();
        var info = faceDetector.Detect(bitmap).First();
        var result = faceRecognizer.Extract(faceImage, faceMark.Mark(faceImage, info)).ToList();

        return result;
    }
</pre>
</details>

**Comment by withsalt** [comment]
docker里面/app/viewfacecore/linux/x64这个目录下面有没有*.so文件?

**Comment by ertu426** [comment]
![image](https://user-images.githubusercontent.com/41768270/187821760-0e3f11bb-8729-47b4-b4c6-b0936af6214c.png)
是有的  我尝试重新构建Docker镜像也会提示有找不到 libSeetaAuthorize.so

<details><summary>Dockfile</summary>
<pre>
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY . .
RUN dotnet restore face_system.sln
RUN dotnet publish  -c Release -o publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /app
RUN apk update
RUN apk add --no-cache libgomp gcompat
RUN apk add libgdiplus --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted
COPY --from=build /src/publish ./
EXPOSE 80
EXPOSE 443
ENTRYPOINT ["dotnet", "face_system.dll"]
</pre>
</details>

**Comment by ertu426** [comment]
可能是 alpine 系统下 有什么包我没安装吧  用 Ubuntu镜像就没问题
